# Generated by Django 3.2.16 on 2022-11-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0001_changed_my_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compagnies',
            options={'verbose_name': 'Compagnie', 'verbose_name_plural': 'Compagnies'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='compagnies',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
