# Generated by Django 3.2.16 on 2022-11-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0002_changed_status_compagnie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnies',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Est Active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='compagnie',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulaires.compagnies', verbose_name='Compagnie'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='N° Téléphone'),
        ),
    ]
