# Generated by Django 3.2.16 on 2022-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0006_add_communes'),
    ]

    operations = [
        migrations.AddField(
            model_name='communes',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Est Active'),
        ),
        migrations.AddField(
            model_name='pays',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Est Active'),
        ),
        migrations.AddField(
            model_name='villes',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Est Active'),
        ),
    ]
