# Generated by Django 3.2.16 on 2022-11-19 11:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0007_add_status_on_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='communes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 513389, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='communes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 513389, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='compagnies',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 508390, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='compagnies',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 508390, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 509390, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 509390, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='pays',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 512390, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='pays',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 512390, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='villes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 512390, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='villes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 19, 11, 26, 18, 512390, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='communes',
            name='villes',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulaires.villes', verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='villes',
            name='pays',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulaires.pays', verbose_name='Pays'),
        ),
    ]
