# Generated by Django 3.2.16 on 2022-11-20 11:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('formulaires', '0011_add_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_colis', models.CharField(max_length=100, null=True, verbose_name='N° Colis')),
                ('poids', models.IntegerField(null=True, verbose_name='Poids')),
                ('receveur', models.CharField(max_length=200, verbose_name='Receveur')),
                ('adresse_receveur', models.CharField(max_length=200, verbose_name='Adresse du receveur')),
                ('date_arrive', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée")),
                ('date_depart', models.DateField(blank=True, null=True, verbose_name='Date de départ')),
                ('quartier', models.CharField(max_length=200, verbose_name='Quartier')),
                ('etape', models.IntegerField(default=0, null=True, verbose_name='Etape')),
                ('type_table', models.CharField(default='COL', max_length=5, null=True, verbose_name='Type Table')),
                ('photo', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('status', models.BooleanField(default=True, verbose_name='Est Active')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 9988, tzinfo=utc), verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 9988, tzinfo=utc), verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Colis',
                'verbose_name_plural': 'Colis',
            },
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 8988, tzinfo=utc), verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 8988, tzinfo=utc), verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='communes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 7988, tzinfo=utc), verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='communes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 7988, tzinfo=utc), verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='compagnies',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 987, tzinfo=utc), verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='compagnies',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 987, tzinfo=utc), verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 5986, tzinfo=utc), verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 5986, tzinfo=utc), verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='villes',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 6988, tzinfo=utc), verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='villes',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 20, 11, 15, 6, 6988, tzinfo=utc), verbose_name='Date de mise à jour'),
        ),
    ]
